### ISSUE TITLE
[DOKS-Egress-Gateway] Add SSH key example for the egress gateway CRD

### ISSUE THREAD

**Issue by udhay45** [digitalocean/container-blueprints#54]
1. Document ssh setup configuration (add ssh key to the setup) for the user
When we create the nat-gw via crossplane, I can't ssh to it as we need to add the fingerprint to the userdata. 
I had to get the fingerprint from UI Console Settings --> Security --> SSH Keys --> copy fingerprint and use it in the nat-gw yaml. 

--
  forProvider:
    region: nyc3
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
    sshKeys:
      - bb:bb:bb:bb:bb:bb:bb:bb 

2. verify “ssh’ing” works
I did this by "ssh root@public_ip_of_NAT_GW -i .ssh/<private_ssh_key>

3. Verify ip_forwarding is enabled
"sysctl net.ipv4.ip_forward" 

Expected output 
net.ipv4.ip_forward = 1

4. verify nat is enabled
"iptables -L -t nat" 

Expected output:
root@nat-gw-nyc3-new5:~# iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  10.108.0.0/20        anywhere. --->  Should see the the VPC network info where you have both NAT GW and the K8s cluster

**Comment by v-ctiutiu** [comment]
Thanks @udhay45.

Fixed via #56. 

Please re-open if the case.
